version: 52

jobs:
- name: build et push image docker
  steps:
  - !CheckoutStep
    name: récupération du dépôt
    cloneCredential: !DefaultCredential {}
    withLfs: false
    withSubmodules: false
    condition: SUCCESSFUL

  - !BuildImageStep
    name: build + push image
    output: !RegistryOutput
      tags: "@server@/rtorrent-flood-image/rtorrent-flood:@tag@ @server@/rtorrent-flood-image/rtorrent-flood:latest docker.io/axolotty/rtorrent-flood:@tag@ docker.io/axolotty/rtorrent-flood:latest"
    registryLogins:
    - registryUrl: "@server_url@"
      userName: "@job_token@"
      passwordSecret: onedev-registry-token
    - registryUrl: ""
      userName: axolotty
      passwordSecret: dockerhub-token
    platforms: linux/amd64
    condition: SUCCESSFUL

  triggers:
  - !TagCreateTrigger
    tags: "v*"
  retryCondition: never
